### ISSUE TITLE
Config option to not override with empty values

### ISSUE THREAD

**Issue by sigurdblueface** [TwiN/deepmerge#5]
### Describe the feature request

so imagine we have a 'base' yaml file
```yaml
app:
  name: base
  vault: 
    url: url
    path: path
```
we have an 'override' yaml file
```yaml
app:
  name: api
  vault: {}
```
we're unmarshalling these into `map[string]interface{}`

on merge 

```go
err = deepmerge.DeepMerge(<map with base app>, <map with override app>, mergeConfig)
if err != nil {
  return err
}
```

we have as a result:
```yaml
app:
  name: api
  vault: {}
```
it seems pretty logical indeed, but It would be great to have that behaviour configurable. 

### Why do you personally want this feature to be implemented?

in order not to write `omitempty` to every yaml structure
